theme: jekyll-theme-minimal
title: DGL Solutions | UK-based technology and e-commerce consultancy
description: Providing technology and e-commerce consulting services to UK businesses of all sizes (startup to multi-national).
